//texto lorem
const text = [
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ante dui, finibus ac pellentesque vitae, venenatis et est. Fusce quis lacus sed mi ornare tempus. Pellentesque sit amet metus vel lectus consequat auctor id sit amet nisl. Ut auctor massa risus, non vehicula lorem maximus eget. Donec in lacus sapien. Integer leo erat, faucibus a gravida nec, dictum vitae dui. Mauris arcu felis, aliquet et interdum vel, tincidunt id sapien. Phasellus finibus bibendum tellus vitae mollis. Pellentesque gravida nibh sit amet purus luctus luctus. Mauris at cursus libero, eu tincidunt risus. Proin aliquet aliquam pulvinar. Vivamus interdum dolor nec eros malesuada accumsan. Morbi viverra a eros quis ornare. Donec tempor nulla finibus enim viverra elementum. Sed facilisis, nunc eu tempor dictum, sem mauris efficitur nulla, vitae condimentum sapien nisl sit amet neque. Curabitur non ante congue, dignissim ligula malesuada, tempus justo.`,
  `Maecenas non magna eros. Integer venenatis nec mi id volutpat. Proin lorem leo, auctor quis cursus eu, ullamcorper eget ante. Duis a lobortis dui. In magna libero, iaculis eu iaculis sed, laoreet eu lorem. Aliquam aliquam rhoncus quam, tristique viverra augue faucibus id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed commodo eros, eu aliquet eros. Cras egestas aliquam lorem, sit amet molestie urna pharetra ac. Ut vel ante facilisis, iaculis ligula quis, fringilla neque.`,
  `Duis ante purus, rutrum ut sagittis bibendum, suscipit at nulla. Aliquam eget nulla eu lacus pretium faucibus at in lacus. Morbi tempus in lorem in lobortis. Aliquam mattis est eget elementum porttitor. Quisque bibendum, eros lacinia ornare volutpat, nisl dui volutpat quam, aliquet consectetur metus velit consequat dui. Cras quam dui, auctor nec dolor dapibus, efficitur molestie mauris. Fusce ipsum dolor, sagittis et ipsum id, condimentum rutrum lorem. Curabitur sollicitudin accumsan facilisis. Proin sit amet dignissim justo. Duis iaculis consectetur vehicula. Aenean luctus risus ac vestibulum maximus. Vivamus lobortis neque ut erat consequat, non malesuada dui faucibus. Ut auctor id risus ut porttitor. Nullam eget tempus nulla. Integer ac dui in justo condimentum lobortis ut malesuada dolor. Sed id dolor mollis, vestibulum nunc elementum, vestibulum mi.`,
  `Aenean felis orci, scelerisque eu consectetur at, scelerisque nec sem. Vivamus suscipit sapien vel tellus ultricies imperdiet. In vulputate vestibulum ex, at volutpat justo feugiat consectetur. Suspendisse finibus ipsum non consequat semper. Aliquam erat volutpat. Integer sit amet molestie velit. Nam a pellentesque risus. Nullam a venenatis eros, nec maximus tortor. Aenean nec magna a dui gravida dictum eu vitae leo. Maecenas sit amet sagittis nisl. Etiam faucibus viverra tellus, vel porta nisl vehicula vitae. Suspendisse potenti. Vestibulum posuere varius eleifend.`,
  `Sed ac sem ac sem luctus maximus eget id metus. Duis tellus mauris, tempus quis porta eu, dapibus eu odio. In hac habitasse platea dictumst. In euismod varius auctor. Donec pellentesque erat ut justo maximus bibendum. Curabitur ac sapien dignissim, ultricies tellus et, fermentum velit. Curabitur interdum ligula eget justo consequat hendrerit. Donec pulvinar vitae quam in pellentesque. Cras molestie libero aliquam dolor sollicitudin scelerisque. Mauris felis est, fringilla eu mauris eu, porttitor fringilla lectus. Proin et euismod augue.`,
  `Donec ut nisl luctus, fermentum ipsum quis, lacinia ex. Pellentesque eu mauris nisi. Maecenas quis tincidunt dui. Praesent vitae nisi at ex accumsan tempus sit amet blandit mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus aliquet laoreet purus. Aliquam quis consectetur ante, nec vehicula urna. Phasellus justo lacus, placerat varius nibh id, blandit tempor sapien. Proin lacinia lorem augue, vitae feugiat tortor efficitur porttitor. Sed sollicitudin, nunc quis faucibus fermentum, ipsum arcu tempor est, ornare efficitur erat mi et mauris. Sed et eros ac neque facilisis cursus. Mauris condimentum nibh eget neque euismod ullamcorper. Suspendisse a cursus mauris, non lobortis purus.`,
  `Ut condimentum turpis aliquam sapien lacinia, id aliquet nulla sollicitudin. Sed varius lacus sed leo facilisis cursus. Donec dictum mauris mollis, mollis mi nec, ornare mi. Praesent vel vulputate ante. Vestibulum ac aliquet enim. Aenean sit amet efficitur nisi, ut posuere enim. Curabitur ultricies tellus eget felis luctus tincidunt. Aliquam tempus sapien augue, nec pellentesque nibh tempor nec. Proin urna nisl, scelerisque vitae dui viverra, finibus aliquet sapien. Pellentesque eget dictum nibh. In porta mauris risus, maximus lacinia nisl dictum vitae. Suspendisse potenti. Aenean non nisl ullamcorper, commodo ligula eu, aliquet lectus. Integer rutrum id elit eu mollis.`,
  `Duis dapibus interdum sodales. Nam vel quam posuere, feugiat erat ut, convallis dui. Etiam blandit, ligula commodo vestibulum vulputate, ante diam accumsan arcu, sit amet consequat odio metus eget libero. In vitae dui purus. Curabitur arcu risus, egestas eget semper eget, aliquam et nulla. Quisque malesuada fringilla dui, id eleifend erat porttitor id. Nullam at ex pellentesque, semper mauris nec, bibendum arcu. Sed accumsan metus at lorem laoreet, ut molestie risus vehicula. Praesent placerat elit ut leo laoreet lacinia. Pellentesque at sapien non ipsum volutpat aliquet ac eget lectus.`,
  `Aliquam erat volutpat. Donec nec massa condimentum, sollicitudin lectus a, efficitur ante. Phasellus sed vehicula lorem. In dapibus metus ex, sed rhoncus lorem finibus in. Ut sollicitudin in nisl vel interdum. Pellentesque leo risus, egestas ut pellentesque nec, suscipit et metus. Mauris a consequat urna. Proin mollis tortor nulla, eu gravida urna feugiat sit amet. Nullam vitae malesuada diam. Quisque mi orci, ultrices non dui id, congue porttitor neque. Duis consectetur ligula id sodales congue. Donec ut nisl vel lorem luctus hendrerit. Pellentesque eu neque sed ante mollis posuere. Fusce nisi neque, laoreet vitae interdum et, consectetur sit amet justo. Donec sit amet dui ac felis pulvinar feugiat vitae nec ligula.`,
];
const form = document.querySelector(".lorem-form");
const amount = document.getElementById("amount");
const result = document.querySelector(".lorem-text");

form.addEventListener("submit", function textAppear(e) {
  e.preventDefault();
  const value = parseInt(amount.value);
  const random = Math.floor(Math.random() * text.length);

  if (isNaN(value) || value <= 0 || value > 9) {
    result.innerHTML = `<p class="result">${text[random]}</p>`;
  } else {
    let tempText = text.slice(0, value);
    tempText = tempText.map(function (item) {
        return `<p class="result">${item}</p>`;
      })
      .join("");
    result.innerHTML = tempText;
  }
});